org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=2G -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true
# ?? java 17
 org.gradle.java.home=/Library/Java/JavaVirtualMachines/openjdk-17.jdk/Contents/Home
#org.gradle.java.home=/Users/mac/Library/Java/JavaVirtualMachines/corretto-11.0.26/Contents/Home